// lib/ai/topicBank.ts
//
// GENERATED by scripts/import-topic-bank.mjs from a source workbook — do
// not hand-edit; re-run the script and commit its output instead. The
// source itself is not committed (source material, not code); see that
// script's own header for what was kept from it and what was left out.
//
// This is a browsing/prompt-seed list, not copy: buildTopicBrief() (in
// this file) turns a (topic, shape) pick into a Hebrew brief for the SAME
// pipeline a typed brief goes through (lib/ai/postGenerator.ts's
// buildGeneratePrompt) — real, non-formulaic copy written per request,
// grounded in her actual services, in her voice, every time.

import type { FieldKey } from '../businessFields.ts';

export type ShapeKey = "tip" | "audience_question" | "myth_vs_reality" | "behind_the_treatment" | "booking_invitation";
export type Channel = 'post_story' | 'carousel' | 'reel_post';

export type ShapeMeta = { label: string; goal: string; channel: Channel };

// goal and channel are fixed per shape across the whole source sheet
// (verified, not assumed — every one of the 365 rows agrees), so they
// live once here rather than repeating on all 73 topics.
//
// channel: 'carousel' (מיתוס מול מציאות) has no real multi-slide
// mechanism in this product yet — Template.format is feed45 | story |
// square, nothing swipeable. buildTopicBrief() below approximates it: a
// single collage-style canvas holding both the myth line and the reality
// line, not a real Instagram carousel. Logged, not silently substituted —
// see WORK_PLAN.md's "רעיונות לעתיד" for the real-carousel item.
export const SHAPE_META: Record<ShapeKey, ShapeMeta> = {
  tip: { label: "טיפ קצר", goal: "שמירה ומעורבות", channel: "post_story" },
  audience_question: { label: "שאלת קהל", goal: "תגובות", channel: "post_story" },
  myth_vs_reality: { label: "מיתוס מול מציאות", goal: "חינוך ואמון", channel: "carousel" },
  behind_the_treatment: { label: "מאחורי הטיפול", goal: "היכרות ואמון", channel: "reel_post" },
  booking_invitation: { label: "הזמנה לתור", goal: "פניות והזמנות", channel: "post_story" },
};

export type Topic = {
  id: string;
  field: FieldKey;
  name: string;
  /** One short Hebrew line — a STARTING POINT for a real photoSlot hint
   *  or Claude's own imageSubject, the same for every shape (verified: it
   *  never varies by shape in the source sheet). Never sent to a client
   *  as-is; buildTopicBrief() below folds it into a brief, not a caption. */
  visualSeed: string;
};

export const TOPIC_BANK: Topic[] = [
  { id: "cosmetics-01", field: "cosmetics", name: "ניקוי פנים ראשון", visualSeed: "צילום סביבת הטיפול והעמדה המסודרת" },
  { id: "cosmetics-02", field: "cosmetics", name: "אקנה בגיל ההתבגרות", visualSeed: "שלושה מוצרים על רקע נקי" },
  { id: "cosmetics-03", field: "cosmetics", name: "אקנה בגיל מבוגר", visualSeed: "צילום תכשירים עם כותרת אקנה אחרי גיל 25" },
  { id: "cosmetics-04", field: "cosmetics", name: "פצעונים בגב", visualSeed: "צילום גב באיור מאויר ללא זיהוי" },
  { id: "cosmetics-05", field: "cosmetics", name: "כתמי פוסט אקנה", visualSeed: "איור השוואה בין כתם למרקם" },
  { id: "cosmetics-06", field: "cosmetics", name: "צלקות אקנה", visualSeed: "תקריב מרקם עור בהסכמה" },
  { id: "cosmetics-07", field: "cosmetics", name: "פיגמנטציה", visualSeed: "בקבוק SPF לצד חלון מואר" },
  { id: "cosmetics-08", field: "cosmetics", name: "מלזמה", visualSeed: "רקע עדין עם כתמי צבע מדורגים" },
  { id: "cosmetics-09", field: "cosmetics", name: "עור יבש", visualSeed: "טיפת סרום ותקריב מרקם" },
  { id: "cosmetics-10", field: "cosmetics", name: "עור מיובש", visualSeed: "שתי טיפות מים על זכוכית" },
  { id: "cosmetics-11", field: "cosmetics", name: "עור רגיש", visualSeed: "מוצרים מינימליסטיים על בד רך" },
  { id: "cosmetics-12", field: "cosmetics", name: "מחסום העור", visualSeed: "איור שכבות עור עדין" },
  { id: "cosmetics-13", field: "cosmetics", name: "נקבוביות", visualSeed: "תקריב עור טבעי ללא פילטר" },
  { id: "cosmetics-14", field: "cosmetics", name: "קומדונים", visualSeed: "צילום כלי טיפול מקצועיים" },
  { id: "cosmetics-15", field: "cosmetics", name: "שגרת בוקר", visualSeed: "שלושה מוצרים מסודרים בשורה" },
  { id: "cosmetics-16", field: "cosmetics", name: "שגרת ערב", visualSeed: "שידת לילה עם מוצרי טיפוח" },
  { id: "cosmetics-17", field: "cosmetics", name: "קרם הגנה", visualSeed: "בקבוק SPF בתיק" },
  { id: "cosmetics-18", field: "cosmetics", name: "פילינג ביתי", visualSeed: "מוצר פילינג לצד לוח שבועי" },
  { id: "cosmetics-19", field: "cosmetics", name: "הכנה לאירוע", visualSeed: "יומן עם תאריך אירוע" },
  { id: "cosmetics-20", field: "cosmetics", name: "אחרי טיפול פנים", visualSeed: "כרטיס הנחיות ליד מוצרי בית" },
  { id: "cosmetics-21", field: "cosmetics", name: "עיסוי פנים", visualSeed: "תקריב ידיים בעיסוי בהסכמה" },
  { id: "cosmetics-22", field: "cosmetics", name: "טיפול עונתי", visualSeed: "מוצרים לצד פריט עונתי" },
  { id: "cosmetics-23", field: "cosmetics", name: "עור בוגר", visualSeed: "דיוקן טבעי ומכבד של עור בוגר" },
  { id: "cosmetics-24", field: "cosmetics", name: "מרקם לא אחיד", visualSeed: "צילום תקריב עור טבעי" },
  { id: "cosmetics-25", field: "cosmetics", name: "אדמומיות", visualSeed: "רקע ורוד עדין עם שאלות קצרות" },
  { id: "cosmetics-26", field: "cosmetics", name: "פגישת אבחון", visualSeed: "צילום מחברת אבחון ועט" },
  { id: "cosmetics-27", field: "cosmetics", name: "מיתוס מחיר מוצר", visualSeed: "שני בקבוקים ללא מותג" },
  { id: "cosmetics-28", field: "cosmetics", name: "פחות מוצרים", visualSeed: "מדף מסודר עם שלושה מוצרים" },
  { id: "cosmetics-29", field: "cosmetics", name: "עקביות בטיפול", visualSeed: "יומן התקדמות וצילום באותה תאורה" },
  { id: "cosmetics-30", field: "cosmetics", name: "לפני ואחרי אחראי", visualSeed: "מסגרת כפולה עם תאורה שווה" },
  { id: "cosmetics-31", field: "cosmetics", name: "שאלות על טיפול", visualSeed: "בועות שאלות על רקע קליניקה" },
  { id: "cosmetics-32", field: "cosmetics", name: "טיפול לגברים", visualSeed: "צילום פינת הטיפול ניטרלית" },
  { id: "cosmetics-33", field: "cosmetics", name: "היגיינה בקליניקה", visualSeed: "עמדה נקייה לפני לקוחה" },
  { id: "cosmetics-34", field: "cosmetics", name: "מתנה של זמן לעצמך", visualSeed: "מגבת נקייה ונר ללא להבה" },
  { id: "cosmetics-35", field: "cosmetics", name: "לקוחות חוזרות", visualSeed: "כרטיס לקוחה ללא פרטים מזהים" },
  { id: "cosmetics-36", field: "cosmetics", name: "טיפול בהתאמה אישית", visualSeed: "שני כרטיסי תכנית שונים" },
  { id: "cosmetics-37", field: "cosmetics", name: "פתיחת יומן טיפולים", visualSeed: "צילום יומן עם חלונות פנויים" },
  { id: "nails-01", field: "nails", name: "מניקור ראשון", visualSeed: "עמדת מניקור מסודרת" },
  { id: "nails-02", field: "nails", name: "בחירת צורה", visualSeed: "שלוש צורות ציפורניים זו לצד זו" },
  { id: "nails-03", field: "nails", name: "אורך פרקטי", visualSeed: "ידיים על מקלדת" },
  { id: "nails-04", field: "nails", name: "בסיס שקוף", visualSeed: "מניקור שקוף באור יום" },
  { id: "nails-05", field: "nails", name: "פרנץ קלאסי", visualSeed: "תקריב פרנץ מדויק" },
  { id: "nails-06", field: "nails", name: "פרנץ צבעוני", visualSeed: "חמישה קצוות בצבעים שונים" },
  { id: "nails-07", field: "nails", name: "גווני ניוד", visualSeed: "מניפת ניוד על כמה גוני עור" },
  { id: "nails-08", field: "nails", name: "אדום קלאסי", visualSeed: "שלושה גווני אדום על דוגמיות" },
  { id: "nails-09", field: "nails", name: "ציפורניים קצרות", visualSeed: "תקריב ציפורניים קצרות מעוצבות" },
  { id: "nails-10", field: "nails", name: "ציפורניים טבעיות", visualSeed: "צילום טבעי של ידיים" },
  { id: "nails-11", field: "nails", name: "לק ג׳ל", visualSeed: "תקריב קו צמיחה של לק ג׳ל" },
  { id: "nails-12", field: "nails", name: "הסרה מקצועית", visualSeed: "צילום כלי הסרה מקצועיים" },
  { id: "nails-13", field: "nails", name: "הרגלי בית", visualSeed: "בקבוק שמן לידיים" },
  { id: "nails-14", field: "nails", name: "ציפורן שנשברה", visualSeed: "צילום ציפורן שבורה מאוירת" },
  { id: "nails-15", field: "nails", name: "התאמת צבע לעונה", visualSeed: "פלטת צבעים עונתית" },
  { id: "nails-16", field: "nails", name: "צבע לחופשה", visualSeed: "מזוודה ומניפת צבעים" },
  { id: "nails-17", field: "nails", name: "ציפורניים לאירוע", visualSeed: "יומן אירוע ומניפת צבעים" },
  { id: "nails-18", field: "nails", name: "כלות", visualSeed: "יד עם טבעת ודוגמיות עדינות" },
  { id: "nails-19", field: "nails", name: "עיצוב מינימליסטי", visualSeed: "דוגמית עם קו עדין" },
  { id: "nails-20", field: "nails", name: "עיצוב נועז", visualSeed: "קולאז׳ של עיצובים צבעוניים" },
  { id: "nails-21", field: "nails", name: "כרום", visualSeed: "תקריב גימור כרום" },
  { id: "nails-22", field: "nails", name: "מאט או מבריק", visualSeed: "שתי דוגמיות באותו צבע" },
  { id: "nails-23", field: "nails", name: "אבנים וקישוטים", visualSeed: "דוגמיות עם קישוט מדורג" },
  { id: "nails-24", field: "nails", name: "פדיקור אסתטי", visualSeed: "עמדת פדיקור נקייה" },
  { id: "nails-25", field: "nails", name: "צבע ברגליים", visualSeed: "מניפת שני צבעים משלימים" },
  { id: "nails-26", field: "nails", name: "היגיינת כלים", visualSeed: "כלים מסודרים בעמדה" },
  { id: "nails-27", field: "nails", name: "תיאום ציפיות", visualSeed: "טלפון עם תמונת השראה ליד דוגמיות" },
  { id: "nails-28", field: "nails", name: "תקציב לעיצוב", visualSeed: "מניפת עיצובים בשלוש רמות" },
  { id: "nails-29", field: "nails", name: "השראה מול מציאות", visualSeed: "צילום השראה לצד תוצאה מותאמת" },
  { id: "nails-30", field: "nails", name: "מילוי או הסרה", visualSeed: "שני כרטיסים מילוי והסרה" },
  { id: "nails-31", field: "nails", name: "ידיים עובדות", visualSeed: "ידיים בעבודה יומיומית" },
  { id: "nails-32", field: "nails", name: "בחירת צבע מהירה", visualSeed: "שלוש דוגמיות נבחרות" },
  { id: "nails-33", field: "nails", name: "לקוחות חוזרות", visualSeed: "אלבום גוונים בטלפון" },
  { id: "nails-34", field: "nails", name: "תור הבא", visualSeed: "יומן עם תור מסומן" },
  { id: "nails-35", field: "nails", name: "מאחורי הקלעים", visualSeed: "שלבי הכנה בעמדה" },
  { id: "nails-36", field: "nails", name: "פתיחת יומן ציפורניים", visualSeed: "יומן פתוח עם זמני תור" },
];

export function topicsForField(fields: FieldKey[]): Topic[] {
  return TOPIC_BANK.filter((t) => fields.includes(t.field));
}

export function findTopic(id: string): Topic | null {
  return TOPIC_BANK.find((t) => t.id === id) || null;
}

/**
 * A (topic, shape) pick, turned into a Hebrew brief for
 * lib/ai/postGenerator.ts's buildGeneratePrompt — the exact pipeline a
 * typed brief goes through, so a topic-bank pick gets a real, freshly
 * written post, grounded in her actual services and voice, never the
 * source sheet's one-sentence-in-five-shells text.
 */
export function buildTopicBrief(topic: Topic, shape: ShapeKey): string {
  const meta = SHAPE_META[shape];
  const seed = topic.visualSeed;
  const shapeInstruction: Record<ShapeKey, string> = {
    tip: `טיפ קצר וברור על "${topic.name}". משהו שאפשר ליישם היום.`,
    audience_question: `שאלה פתוחה ללקוחות על "${topic.name}", שמזמינה תגובות בלי לדרוש ידע מוקדם.`,
    myth_vs_reality: `מיתוס נפוץ על "${topic.name}" מול המציאות — שתי שורות ברורות, מיתוס ואז מציאות, באותה תמונה (עדיין אין אצלנו קרוסלה אמיתית — קומפוזיציה אחת שמכילה את שתיהן).`,
    behind_the_treatment: `הצצה אמיתית לאיך זה עובד אצלה, בהקשר של "${topic.name}" — לא הבטחה, תחושה של להיות שם.`,
    booking_invitation: `הזמנה לתור סביב "${topic.name}", חמה ולא לוחצת.`,
  };
  return [
    shapeInstruction[shape],
    `השראה חזותית (לא טקסט סופי, רק כיוון): ${seed}.`,
    `מטרת הפוסט: ${meta.goal}.`,
  ].join(' ');
}
